from tkinter import *
def click(event):
    text=event.widget.cget("text")
    print(text)
    if text == "=":
        if sc_value.get().isdigit():
            value=int(sc_value.get())
        else:
            try:
                value = eval(screen.get())

            except Exception as e:
                print(e)
                value="Error"

        sc_value.set(value)
        screen.update()
    elif text == "c":
        sc_value.set("")
        screen.update()
    else:
        sc_value.set(sc_value.get() + text)
        screen.update()

root = Tk()
root.title(" Calculator by Vamshi krishna")
root.geometry("900x800")
sc_value = StringVar()
sc_value.set("")
screen = Entry(root, textvariable=sc_value, font="lucida 40 bold")
screen.pack(fill=X, padx=10, pady=10)
f = Frame(root, bg="grey")
b = Button(f, text="9", font="lucida 25 bold", padx=5, pady=5)
b.pack(side=LEFT, padx=5, pady=5)
b.bind("<Button-1>",click)
b = Button(f, text="7", font="lucida 25 bold", padx=5, pady=5)
b.pack(side=LEFT, padx=5, pady=5)
b.bind("<Button-1>",click)
b = Button(f, text="8", font="lucida 25 bold", padx=5, pady=5)
b.pack(side=LEFT, padx=5, pady=5)
b.bind("<Button-1>",click)
f.pack()

f = Frame(root, bg="grey")
b = Button(f, text="7", font="lucida 25 bold", padx=5, pady=5)
b.pack(side=LEFT, padx=5, pady=5)
b.bind("<Button-1>",click)
b = Button(f, text="6", font="lucida 25 bold", padx=5, pady=5)
b.pack(side=LEFT, padx=5, pady=5)
b.bind("<Button-1>",click)
b = Button(f, text="5", font="lucida 25 bold", padx=5, pady=5)
b.pack(side=LEFT, padx=5, pady=5)
b.bind("<Button-1>",click)
f.pack()

f = Frame(root, bg="grey")
b = Button(f, text="4", font="lucida 25 bold", padx=5, pady=5)
b.pack(side=LEFT, padx=5, pady=5)
b.bind("<Button-1>",click)
b = Button(f, text="3", font="lucida 25 bold", padx=5, pady=5)
b.pack(side=LEFT, padx=5, pady=5)
b.bind("<Button-1>",click)
b = Button(f, text="2", font="lucida 25 bold", padx=5, pady=5)
b.pack(side=LEFT, padx=5, pady=5)
b.bind("<Button-1>",click)
f.pack()

f = Frame(root, bg="grey")
b = Button(f, text="1", font="lucida 25 bold", padx=5, pady=5)
b.pack(side=LEFT, padx=5, pady=5)
b.bind("<Button-1>",click)
b = Button(f, text="0", font="lucida 25 bold", padx=5, pady=5)
b.pack(side=LEFT, padx=5, pady=5)
b.bind("<Button-1>",click)
b = Button(f, text="+", font="lucida 25 bold", padx=5, pady=5)
b.pack(side=LEFT, padx=5, pady=5)
b.bind("<Button-1>",click)
f.pack()

f = Frame(root, bg="grey")
b = Button(f, text="-", font="lucida 25 bold", padx=5, pady=5)
b.pack(side=LEFT, padx=5, pady=5)
b.bind("<Button-1>",click)
b = Button(f, text="*", font="lucida 25 bold", padx=5, pady=5)
b.pack(side=LEFT, padx=5, pady=5)
b.bind("<Button-1>",click)
b = Button(f, text="%", font="lucida 25 bold", padx=5, pady=5)
b.pack(side=LEFT, padx=5, pady=5)
b.bind("<Button-1>",click)
f.pack()

f = Frame(root, bg="grey")
b = Button(f, text=".", font="lucida 25 bold", padx=5, pady=5)
b.pack(side=LEFT, padx=5, pady=5)
b.bind("<Button-1>",click)
b = Button(f, text="c", font="lucida 25 bold", padx=5, pady=5)
b.pack(side=LEFT, padx=5, pady=5)
b.bind("<Button-1>",click)
b = Button(f, text="=", font="lucida 25 bold", padx=5, pady=5)
b.pack(side=LEFT, padx=5, pady=5)
b.bind("<Button-1>",click)
f.pack()
root.mainloop()

