from tkinter import *
root=Tk()
root.title("DANCE CLASS FORM :")
root.geometry("500x400")
label_l1=Label(text=" PLS FILL THE FORM WITH CASE SENSITIVE ",bg="yellow",fg="brown")
label_l1.grid(row=0,column=2)
label_l2=Label(text="Enter your name : ",font=("comicsansms",11,"bold"),fg="red")
label_l2.grid(row=2,column=0)
label_l3=Label(text="Enter your gmail id :",font=("comicsansms",11,"bold"),fg="red")
label_l3.grid(row=3,column=0)
label_l4=Label(text="Enter your ph.no : ",font=("comicsansms",11,"bold"),fg="red")
label_l4.grid(row=4,column=0)
label_l5=Label(text="Enter your join date :",font=("comicsansms",11,"bold"),fg="red")
label_l5.grid(row=5,column=0)
input_name=StringVar()
input_gmail=StringVar()
input_phno=StringVar()
input_joindate=StringVar()
name_entry=Entry(root,textvariable=input_name)
name_entry.grid(row=2,column=1)
gmail_entry=Entry(root,textvariable=input_gmail)
gmail_entry.grid(row=3,column=1)
phno_entry=Entry(root,textvariable=input_phno)
phno_entry.grid(row=4,column=1)
joindate_entry=Entry(root,textvariable=input_joindate)
joindate_entry.grid(row=5,column=1)
def get_info():
    print(f'your name is : {name_entry.get()}')
    print(f'your gmail is :{gmail_entry.get()}')
    print(f'your ph.no is :{phno_entry.get()}')
    print(f'your joindata is :{joindate_entry.get()}')
    print("\n")
button_b1=Button(text="Submit",command=get_info)
button_b1.grid(row=6,column=1)

root.mainloop()