from tkinter import *
root=Tk()
root.title("PY-charm")
root.geometry("500x400")
main_menu=Menu(root)
text_menu=Menu(main_menu,tearoff=0)
text_menu.add_command(label="New project")
text_menu.add_command(label="New")
text_menu.add_command(label="save")
text_menu.add_command(label="open")
text_menu.add_command(label="setting")
edit_menu=Menu(main_menu,tearoff=0)
edit_menu.add_command(label="cut")
edit_menu.add_command(label="copy")
edit_menu.add_command(label="delete")
edit_menu.add_command(label="find")
view_menu=Menu(main_menu,tearoff=0)
view_menu.add_command(label="Tool window")
view_menu.add_command(label="Tool bar")
view_menu.add_command(label="Recent files")
run_menu=Menu(main_menu,tearoff=0)
run_menu.add_command(label="Run")
run_menu.add_command(label="debug")
window_menu=Menu(main_menu,tearoff=0)
window_menu.add_command(label="Notifications")
window_menu.add_command(label="Background Task")
help_menu=Menu(main_menu,tearoff=0)
help_menu.add_command(label="Help")
help_menu.add_command(label="contact support")
help_menu.add_command(label="About")
root.config(menu=main_menu)
main_menu.add_cascade(label="Files",menu=text_menu)
main_menu.add_cascade(label="Edit",menu=edit_menu)
main_menu.add_cascade(label="View",menu=view_menu)
main_menu.add_cascade(label="Run",menu=run_menu)
main_menu.add_cascade(label="Window",menu=window_menu)
main_menu.add_cascade(label="Help",menu=help_menu)
root.mainloop()